#!/usr/bin/env bash

declare -a hosts files

hosts=(
    zim
    xxx
)

files=( 
    .bashrc
    .vimrc
    .bash_completion
    .pystartup
    .inputrc
)

for host in "${hosts[@]}" ; do
    remote_cksum=$(ssh $host cksum "${files[@]}" 2> /dev/null)

    # check if error occurred connection to server
    if [[ $? = 255 ]] ; then
        echo "$0: Could not connect to $host" 1>&2
        continue
    fi

    for file in "${files[@]}" ; do
        # if checksum matched, upload
        if grep -qx "$(cksum $file)" <<<"$remote_cksum" ; then : ; else
            echo scp $file $host:$file
        fi
    done
done
