#!/usr/bin/env bash
#
# Distribute $files to $hosts
# 
# rcdist [-d] [base_dir]
#
#   -d       dry run
#   base_dir base directory (default is $HOME)

declare -a hosts files dirs

hosts=(
    zim
)

files=( 
    .bashrc
    .vimrc
    .bash_completion
    .pystartup
    .inputrc
    .screenrc
    .perltidy
    .vim/plugin/minibufexpl_mod.vim
    .vim/ftplugin/perl.vim
)

# get options
dry=

while getopts "d" flag ; do
    case $flag in
        d)  dry=1
            ;;
        ?)  exit 1
            ;;
    esac
done
shift $(( $OPTIND-1 ))

base="$1"
if [[ -z "$base" ]] ; then
    base="$HOME"
fi

# change to base directory
cd "$base"

function elemExists() {
    needle=$1
    shift

    for i in "$@" ; do
        [[ "$i" == "$needle" ]] && exit 0
    done
    return 1
}

# find all the directories that need to be created
for file in "${files[@]}" ; do
    if [[ ! -r "$file" ]] ; then
        echo "$0: Could not read file: $file" 1>&2
        exit 1;
    fi
    dir=${file%/*}

    if [[ "$dir" != "$file" ]] && ! elemExists "$dir" "${dirs[@]}" ; then
        dirs[${#dirs[@]}]="$dir"
    fi
done

for host in "${hosts[@]}" ; do
    echo "Checking host: $host"
    remote_cksum=$(ssh -C "$host" cksum "${files[@]}" ";" mkdir -p "${dirs[@]}" 2> /dev/null)
                              
    # check if error occurred connection to server
    if [[ $? = 255 ]] ; then
        echo "$0: Could not connect to $host" 1>&2
        continue
    fi

    for file in "${files[@]}" ; do
        if ! grep -qx "$(cksum "$file")" <<<"$remote_cksum" ; then
            # if checksum matched, upload
            if [[ -n $dry ]] ; then
                echo "Copy $file"
            else
                scp -C "$file" "$host":"$file"
            fi
        fi
    done
done
