#!/usr/bin/env bash
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

declare -a args

filetype=
filter=

while getopts "c:f:" flag ; do
    case $flag in
        f)  filetype=$OPTARG ;;
        *)  args[${#args[@]}]=$flag
            if [[ -n "$OPTARG" ]] ; then
                args[${#args[@]}]=$OPTARG
            fi
            ;;
    esac
done

shift $(( $OPTIND - 1 ))

# set filetype
if [[ -n "$filetype" ]] ; then
    args=( "${args[@]}" -c "set ft=$filetype" )
    if [[ "$filetype" == man ]] ; then
        filter=1
    fi
fi

# set static options
args=( "${args[@]}" -R --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/my_less.vim' )

# add filenames to argument list
# use stdin if no files
if test $# = 0; then
    args[${#args[@]}]=-
else    
    args=( "${args[@]}" "$@" )
fi

# filter out terminal characters unless told otherwise
if [[ -z "$filter" ]] ; then
    vim "${args[@]}"
else
    col -b | vim "${args[@]}"
fi
